import Navbar from "./components/Navbar";
import localFont from "next/font/local";
import "./globals.css";

import { Inter, Oswald } from "next/font/google";

const inter = Inter({
  subsets: ["latin-ext"],
  display: "swap",
  variable: "--font-inter",
});

const oswald = Oswald({
  subsets: ["latin-ext"],
  display: "swap",
  variable: "--font-oswald",
});

const mitera = localFont({
  src: "./font/Mitera Regular.ttf",
  display: "swap",
  weight: "400",
});
export const metadata = {
  metadataBase: new URL("http://localhost:3000"),
  title: "Zugzwang",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="fr"
      className={`${inter.variable} ${oswald.variable} ${mitera.className}`}
    >
      <body className={`bg-ft-color`}>
        <div className="flex flex-col min-h-screen">
          <Navbar />
          <main className="flex-1">{children}</main>
        </div>
      </body>
    </html>
  );
}
